# Generated by Django 4.2.6 on 2023-10-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(null=True, verbose_name='Nombre')),
                ('Apellido', models.TextField(verbose_name='Apellido')),
                ('Correo', models.TextField(null=True, verbose_name='Correo')),
                ('NumeroTelefono', models.BigIntegerField(null=True, verbose_name='NumeroTelefono')),
            ],
        ),
    ]
