# Generated by Django 4.2.6 on 2023-10-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='NumeroTelefono',
            new_name='Numero',
        ),
    ]
