# Generated by Django 4.2.6 on 2023-10-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_rename_numerotelefono_usuario_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Numero',
            new_name='NumeroTelefono',
        ),
    ]
