# Generated by Django 4.2.6 on 2023-10-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_rename_numero_usuario_numerotelefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Correo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(null=True, verbose_name='Direccion'),
        ),
    ]
